# Generated by Django 4.2.16 on 2025-03-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('web_url', models.URLField(max_length=50)),
                ('user_review', models.TextField()),
                ('rating', models.IntegerField()),
                ('profile_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
